### ISSUE TITLE
NamingMaintainService update instance failed

### ISSUE THREAD

**Issue by chuntaojun** [nacos-group/nacos-spring-project#144]
bug report

### Describe what happened (or what feature you want)

``` java
@NacosInjected
private NamingMaintainService namingMaintainService;

public void updateInstance(boolean enabled) throws NacosException {
        //ignore
        namingMaintainService.updateInstance(serviceName, instance);
 }

java.lang.IllegalArgumentException: no server available
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:439)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:387)
	at com.alibaba.nacos.client.naming.net.NamingProxy.updateInstance(NamingProxy.java:225)
	at com.alibaba.nacos.client.naming.NacosNamingMaintainService.updateInstance(NacosNamingMaintainService.java:86)
	at com.alibaba.nacos.client.naming.NacosNamingMaintainService.updateInstance(NacosNamingMaintainService.java:81)
	at com.alibaba.nacos.spring.factory.DelegatingNamingMaintainService.updateInstance(DelegatingNamingMaintainService.java:46)
```

An error occurred while updating an instance using the above interface

### Describe what you expected to happen

Successful operation

### Tell us your environment

<dependency>
          <groupId>com.alibaba.boot</groupId>
          <artifactId>nacos-discovery-spring-boot-starter</artifactId>
          <version>0.2.3</version>
</dependency>

client 1.1.0

### Anything else we need to know?

``` java
namingMaintainService = NamingMaintainFactory.createMaintainService("127.0.0.1" + ":" + port);
```
If you use it in this way, there is no problem

**Comment by rushsky518** [comment]
@i will solve it@
