### ISSUE TITLE
spring spring项目报403 unknow user

### ISSUE THREAD

**Issue by zhoushaohe** [nacos-group/nacos-spring-project#209]
spring： nacos版本 0.3.6 ， springboot 0.2.6 nacos 0.3.6
测试结果:
spring与Springboot配置相同

    若没加username、password 正常读取配置， 【自己部署的nacos服务】

    若没加username、password 
        spring报403、springboot正常

当然也有可能时这边nacos部署的问题， 但是spring boot与spring 表现不一致。

```
spring
<nacos:global-properties
        server-addr="http://nacos.xxx.cn:8080"  // 无 /
        username="xxx" password="xxx123" namespace="wechat"/>

srpingboot
nacos.config.server-addr=http://nacos.xxx.cn:8080
nacos.config.namespace=wechat
nacos.config.username=xxx
nacos.config.password=xxx123
springboot正常读取配置

spring报错 ， 会是什么问题呢？ 配置应该没错
2020-05-22 19:52:24.943 [RMI TCP Connection(2)-127.0.0.1] ERROR c.a.nacos.spring.util.NacosUtils - Can't get content from dataId : wechat_main , groupId : test
com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri May 22 19:52:24 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:262)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:143)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:92)
	at com.alibaba.nacos.spring.context.event.config.EventPublishingConfigService.getConfig(EventPublishingConfigService.java:60)
```
尝试在nacos服务后加 “/”
```
spring
<nacos:global-properties
        server-addr="http://nacos.xxx.cn:8080/"  // 有 /
        username="xxx" password="xxx123" namespace="wechat"/>
```
这样的配置应该不对，报500， 【下图】此处不应有error日志吗？ 
![image](https://user-images.githubusercontent.com/4318925/82666866-56347900-9c69-11ea-9aef-93a450d7d692.png)

**Comment by zhoushaohe** [comment]
nacos版本 0.3.6 下
nacos-client是1.2.0 ，升级成1.2.1后正常
```
<dependency>
		  <groupId>com.alibaba.nacos</groupId>
		  <artifactId>nacos-spring-context</artifactId>
		  <version>0.3.6</version>
		  <exclusions>
			  <exclusion>
				  <groupId>com.alibaba.nacos</groupId>
				  <artifactId>nacos-client</artifactId>//默认是1.2.0
			  </exclusion>
		  </exclusions>
	  </dependency>
	  <dependency>
		  <groupId>com.alibaba.nacos</groupId>
		  <artifactId>nacos-client</artifactId>
		  <version>1.2.1</version>
	  </dependency>
```
