### ISSUE TITLE
nacos-spring-context的0.3.6版本不支持最新nacos-client

### ISSUE THREAD

**Issue by zhanyao** [nacos-group/nacos-spring-project#214]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
<dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-spring-context</artifactId>
            <version>0.3.6</version>
</dependency>
不支持
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>1.3.1</version>
</dependency>

java.lang.ClassNotFoundException: com.alibaba.nacos.client.config.utils.MD5
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.alibaba.nacos.spring.context.annotation.config.NacosValueAnnotationBeanPostProcessor.onApplicationEvent(NacosValueAnnotationBeanPostProcessor.java:144)
	at com.alibaba.nacos.spring.context.annotation.config.NacosValueAnnotationBeanPostProcessor.onApplicationEvent(NacosValueAnnotationBeanPostProcessor.java:55)
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by Da-Hong** [comment]
着急用的话，自己源码拉下来升级nacos版本

**Comment by wjm0729** [comment]
这个升级也太慢了, 坑死人啊

**Comment by echokk11** [comment]
不打一个RC包到中央仓库吗

**Comment by gang0713** [comment]
这个项目是个烂尾工程吗，没人维护了吗

**Comment by chuntaojun** [comment]
> 这个项目是个烂尾工程吗，没人维护了吗

我已正式上班，非全职维护，如果愿意欢迎共建
