### ISSUE TITLE
使用@NacosConfigListener报错

### ISSUE THREAD

**Issue by paladinGu** [nacos-group/nacos-spring-project#252]
## Issue Description

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.alibaba.nacos.spring.context.event.config.TimeoutNacosConfigListener.receiveConfigInfo(TimeoutNacosConfigListener.java:79)
	at com.alibaba.nacos.client.config.impl.CacheData$1.run(CacheData.java:210)
	at com.alibaba.nacos.client.config.impl.CacheData.safeNotifyListener(CacheData.java:241)
	at com.alibaba.nacos.client.config.impl.CacheData.checkListenerMd5(CacheData.java:181)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:629)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 

### How to reproduce it 
@NacosConfigListener(dataId = "a.properties")
    public void onMsg(Properties config) {

###   environment

 <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-spring-context</artifactId>
            <version>1.0.1</version>
        </dependency>

**Comment by brothelul** [comment]
I will follow on this issue.

**Comment by brothelul** [comment]
@paladinGu the config with properties type will be converted to Map, if you want to use Proeprties to receive the config which in properties type you may appoint your owen converter like the example below.
![image](https://user-images.githubusercontent.com/25661357/116047086-4954ac80-a6a6-11eb-8905-b992d576f5ec.png)
