### ISSUE TITLE
junit单元测试报错  GenericWebApplicationContext  has not been refreshed yet

### ISSUE THREAD

**Issue by yanming1** [nacos-group/nacos-spring-project#273]
## Issue Description

Type: *bug report*

### junit单元测试报错 
Caused by: java.lang.IllegalStateException: org.springframework.web.context.support.GenericWebApplicationContext@3fb1549b has not been refreshed yet
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1141)
	at org.springframework.context.support.AbstractApplicationContext.getBeanNamesForType(AbstractApplicationContext.java:1293)
	at com.alibaba.spring.util.BeanUtils.getBeanNames(BeanUtils.java:153)
	at com.alibaba.spring.util.BeanUtils.getBeanNames(BeanUtils.java:136)
	at com.alibaba.nacos.spring.util.NacosBeanUtils.isBeanDefinitionPresent(NacosBeanUtils.java:207)
	at com.alibaba.nacos.spring.util.NacosBeanUtils.registerInfrastructureBeanIfAbsent(NacosBeanUtils.java:174)
	at com.alibaba.nacos.spring.util.NacosBeanUtils.registerNacosApplicationContextHolder(NacosBeanUtils.java:285)
	at com.alibaba.nacos.spring.util.NacosBeanUtils.registerNacosCommonBeans(NacosBeanUtils.java:372)
	at com.alibaba.nacos.spring.context.annotation.NacosBeanDefinitionRegistrar.registerNacosAnnotationBeans(NacosBeanDefinitionRegistrar.java:83)
	at com.alibaba.nacos.spring.context.config.xml.NacosAnnotationDrivenBeanDefinitionParser.parse(NacosAnnotationDrivenBeanDefinitionParser.java:49)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1391)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1371)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:179)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:149)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:96)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:511)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
	... 37 more

### How to reproduce it (as minimally and precisely as possible)

1.spring.xml 中 import nacos配置
~~~
     <import resource="nacos-config.xml"/>
~~~
2. nacos-config.xml配置如下
<?xml version="1.0" encoding="UTF-8" ?>
        <beans xmlns="http://www.springframework.org/schema/beans" xmlns:nacos="http://nacos.io/schema/nacos"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://nacos.io/schema/nacos http://nacos.io/schema/nacos.xsd
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
     
    
     <nacos:annotation-driven></nacos:annotation-driven>
     
     <nacos:global-properties server-addr="x.x.x.x:8848"/>
     
     <nacos:property-source data-id="projectName" group-id="DEFAULT_GROUP" auto-refreshed="true"/>
 </beans>
3. 启动单元测试
@RunWith(SpringRunner.class)
@SpringJUnitWebConfig
@ContextConfiguration(locations = {"classpath:spring.xml" })
@ActiveProfiles("dev")
public class XTest{
    @Autowired
    private XService xService;

    @Test
    public void testCreate(){
        xService.doBusiness();
    }
}
随便自动注入个服务，然后test方法中调用自动注入服务方法即可
### Tell us your environment
spring版本5.3.6 
nacos-spring-context版本1.1.0

### Anything else we need to know?
对比了一下spring事务注解解析的代码发现不同之处在于
NacosBeanUtils中
	public static void registerInfrastructureBeanIfAbsent(BeanDefinitionRegistry registry,
			String beanName, Class<?> beanClass, Object... constructorArgs) {
		if (!isBeanDefinitionPresent(registry, beanName, beanClass)
				&& !registry.containsBeanDefinition(beanName)) {
			registerInfrastructureBean(registry, beanName, beanClass, constructorArgs);
		}
	}
如上方法在判断是否已注册过bean的时候多了isBeanDefinitionPresent(registry, beanName, beanClass)的判断调用，
而其实现最终会调用AbstractApplicationContext的方法
	public String[] getBeanNamesForType(@Nullable Class<?> type, boolean includeNonSingletons, boolean allowEagerInit) {
		assertBeanFactoryActive();
		return getBeanFactory().getBeanNamesForType(type, includeNonSingletons, allowEagerInit);
	}
此方法中assertBeanFactoryActive()抛出异常，ApplicationContext此时还未执行refresh方法并未激活

**Comment by ChubChen** [comment]
我也遇到这个问题。 请问最后是怎么解决的

**Comment by wushaogen** [comment]
我也遇到这个问题。 请问最后是怎么解决的

**Comment by gingerjiang** [comment]
感觉是应为nacos和spring注解初始化顺序不同，造成的错误，未找到原因，只能用底层的办法先解决问题，先这么测试吧
`public static ApplicationContext context = null;
	
	public static void context() {
		print("*************************** BaseTest ***************************");
		context = new ClassPathXmlApplicationContext("boot-context.xml");
	}
    private static OfflinebakService offlinebakService;
	@BeforeClass
	public static void init() {
		context();
		offlinebakService = context.getBean(OfflinebakService.class);
	}`
