### ISSUE TITLE
适配 snakeyaml2.0

### ISSUE THREAD

**Issue by SuperZ1999** [nacos-group/nacos-spring-project#319]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
nacos-spring-project 适配 snakeyaml2.0

### Tell us your environment
JDK8

**Comment by pdkst** [comment]
补充一点信息：
JDK：21
SpringBoot：3.2.3
nacos版本：0.3.0-RC
snakeyaml·版本：2.2

报错堆栈：
```
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at com.alibaba.nacos.spring.util.parse.DefaultYamlConfigParse.createYaml(DefaultYamlConfigParse.java:66)
	at com.alibaba.nacos.spring.util.parse.DefaultJsonConfigParse.parse(DefaultJsonConfigParse.java:42)
	at com.alibaba.nacos.spring.util.ConfigParseUtils.toProperties(ConfigParseUtils.java:95)
	at com.alibaba.nacos.spring.util.ConfigParseUtils.toProperties(ConfigParseUtils.java:119)
	at com.alibaba.nacos.spring.util.NacosUtils.toProperties(NacosUtils.java:542)
	at com.alibaba.nacos.spring.core.env.NacosPropertySource.<init>(NacosPropertySource.java:62)
	at com.alibaba.boot.nacos.config.binder.NacosBootConfigurationPropertiesBinder.doBind(NacosBootConfigurationPropertiesBinder.java:58)
	at com.alibaba.nacos.spring.context.properties.config.NacosConfigurationPropertiesBinder.bind(NacosConfigurationPropertiesBinder.java:123)
	at com.alibaba.nacos.spring.context.properties.config.NacosConfigurationPropertiesBindingPostProcessor.bind(NacosConfigurationPropertiesBindingPostProcessor.java:91)
	at com.alibaba.nacos.spring.context.properties.config.NacosConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(NacosConfigurationPropertiesBindingPostProcessor.java:68)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
	... 25 more
```

**Comment by dujie-js** [comment]
![image](https://github.com/nacos-group/nacos-spring-project/assets/56857589/10169023-152c-4ae4-aa5f-01f170eb7152)

**Comment by immadolf** [comment]
添加 `-DyamlAllowComplexObject=true` 切换到 Constructor 也报错
<img width="1675" alt="image" src="https://github.com/nacos-group/nacos-spring-project/assets/12369197/7404000b-469e-48fc-80c3-1ffd4bc50445">

**Comment by Jiiiiiin** [comment]
https://mvnrepository.com/artifact/com.alibaba.nacos/nacos-spring-context/2.1.0-RC 找个版本还在在， 0.3.0-RC的间接依赖。
