### ISSUE TITLE
类DeferredApplicationEventPublisher  方法 publishEvent 在4.1.6.RELEASE spring版本时抛异常

### ISSUE THREAD

**Issue by modou1618** [nacos-group/nacos-spring-project#66]
类DeferredApplicationEventPublisher  方法 publishEvent 在4.1.6.RELEASE spring版本时抛异常

**Comment by hhfdna** [comment]
解决了吗？我也遇到同样问题了，怎么解决的？

**Comment by hhfdna** [comment]
您好，我nacos-spring-context中很多类都是您写的。我们目前有一个项目使用了spring4.2.1，也遇到了这个错误
五月 25, 2019 9:26:35 下午 org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
信息: Loading XML bean definitions from ServletContext resource [/WEB-INF/dispatcherServlet-servlet.xml]
21:26:35.845 [localhost-startStop-1] INFO com.alibaba.nacos.client.identify.CredentialWatcher - [] [] [] No credential found
五月 25, 2019 9:26:36 下午 org.springframework.web.servlet.DispatcherServlet initServletBean
严重: Context initialization failed
java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: WebApplicationContext for namespace 'dispatcherServlet-servlet': startup date [Sat May 25 21:26:35 CST 2019]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:414)
	at org.springframework.context.support.AbstractApplicationContext.isRunning(AbstractApplicationContext.java:1282)
	at com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher.publishEvent(DeferredApplicationEventPublisher.java:51)
	at com.alibaba.nacos.spring.core.env.AbstractNacosPropertySourceBuilder.publishMetadataEvent(AbstractNacosPropertySourceBuilder.java:133)
	at com.alibaba.nacos.spring.core.env.AbstractNacosPropertySourceBuilder.build(AbstractNacosPropertySourceBuilder.java:107)
	at com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.buildNacosPropertySources(NacosPropertySourcePostProcessor.java:135)
	at com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.processPropertySource(NacosPropertySourcePostProcessor.java:121)
	at com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.postProcessBeanFactory(NacosPropertySourcePostProcessor.java:107)

**Comment by hhfdna** [comment]
i fixed
https://github.com/alibaba/nacos/issues/1269

**Comment by chuntaojun** [comment]
#102
